# Generated by Django 3.0.5 on 2023-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Specializes in heart-related issues'), ('Cardiologist', 'Specializes in heart-related issues'), ('Dermatologists', 'Specializes in skin-related issues'), ('Dermatologists', 'Specializes in skin-related issues'), ('Emergency Medicine Specialists', 'Handles emergency medical cases'), ('Emergency Medicine Specialists', 'Handles emergency medical cases'), ('Allergists/Immunologists', 'Specializes in allergies and immunology'), ('Allergists/Immunologists', 'Specializes in allergies and immunology'), ('Anesthesiologists', 'Administers anesthesia during medical procedures'), ('Anesthesiologists', 'Administers anesthesia during medical procedures'), ('Colon and Rectal Surgeons', 'Specializes in colorectal surgery'), ('Colon and Rectal Surgeons', 'Specializes in colorectal surgery')], default='Cardiologist', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
